### ISSUE TITLE
[버그] 방화벽 체크 상태 오류

### ISSUE THREAD

**Issue by chaeya** [2020-Invesum-Internship/hamonikr-pcchecker#2]
현재 방화벽을 사용하고 있지 않은 상태인데 체크가 활성으로 나옵니다.

- OS : HamoniKR 3.0 SUN

아래 이미지를 참고해주세요

![선택 영역_259](https://user-images.githubusercontent.com/405502/91277156-69516a80-e7bd-11ea-9d7b-a3fdcf7d3ab5.png)

**Comment by yeji0407** [comment]
해당 오류 수정하여 업데이트 하였습니다. 저희 프로젝트의 부족함을 채워주셔서 감사합니다. 앞으로도 많은 기여 부탁드립니다.
