### ISSUE TITLE
[버그] 시스템에 백업이 있는데도 불구하고 위험으로 보입니다.

### ISSUE THREAD

**Issue by chaeya** [2020-Invesum-Internship/hamonikr-pcchecker#5]
현재 설치된 시스템의 백업 상태는 아래 그림과 같습니다.
OS : HamoniKR 3.0
Tools : Timeshift

![Timeshift_347](https://user-images.githubusercontent.com/405502/94397167-39233000-019e-11eb-8dff-11b833002a7d.png)

하지만 점검도구의 화면은 아래와 같이 나옵니다.
![HamoniKR PC Checker_346](https://user-images.githubusercontent.com/405502/94397219-4fc98700-019e-11eb-889f-80ba2525d389.png)

백업이 있는데도 불구하고 잘못된 표시가 나오는 것 같습니다.

**Comment by yeji0407** [comment]
해당 이슈를 해결하기 위해 백업 설정을 변경한 후 창이 종료되면 결과가 화면에 적용되도록 변경하였습니다. 저희 프로젝트에 기여해 주셔서 감사합니다.
