### ISSUE TITLE
[기능] 업그레이드 가능한 패키지가 있어서 버튼을 누르면 아무런 동작을 하지 않습니다.

### ISSUE THREAD

**Issue by chaeya** [2020-Invesum-Internship/hamonikr-pcchecker#6]
아래 그림의 버튼을 누르면 실제 동작을 하고 있는 중이지만 업그레이 하고 있는 상태를 알수 없어서
프로그램이 오류인것으로 보입니다.

![HamoniKR PC Checker_346](https://user-images.githubusercontent.com/405502/94397305-84d5d980-019e-11eb-85fe-c1ab77bf2e53.png)

버튼을 눌렀을때 프로그램의 업데이트 진행 상태를 보여주는 것이 필요합니다.

**Comment by yeji0407** [comment]
해당 이슈를 해결하기 위하여 빠른 업데이트 버튼을 클릭하여 업데이트가 진행되고 있을 때 이를 알리는 글이 출력되도록 변경하였습니다. 저희 프로젝트에 기여해 주셔서 감사합니다!
