### ISSUE TITLE
[bug] 알람기능 체크가 정상작동하지 않습니다.

### ISSUE THREAD

**Issue by chaeya** [2020-Invesum-Internship/hamonikr-pcchecker#8]
PC에 알람이 설정되어 있는데도 불구하고 알람이 비활성화 된것으로 나타납니다.
아래 이미지를 참고해주세요.
![HamoniKR PC Checker_349](https://user-images.githubusercontent.com/405502/94412175-709cd700-01b4-11eb-9441-5013c19f0be2.png)

**Comment by yeji0407** [comment]
해당 버그를 수정하고 기능을 완성하여 업데이트 하였습니다. 좋은 지적 감사합니다!
